### ISSUE TITLE
LRM-00109: could not open parameter file 'initORCLCDB.ora'

### ISSUE THREAD

**Issue by ahmetsevki** [oracle/adb-free#21]
I am using colima + docker-compose

## 
```
colima delete
colima start --cpu 4 --memory 8 --arch x86_64
docker-compose up
```

Gives me:
```
oracle  | Connected to an idle instance.
oracle  | 
oracle  | SQL> ORA-01078: failure in processing system parameters
oracle  | LRM-00109: could not open parameter file '/u01/app/oracle/product/23.0.0.0/dbhome_1/dbs/initORCLCDB.ora'
oracle  | SQL> Disconnected
oracle  | TIME ELAPSED Database started: 0 minutes and 0 seconds elapsed

```
## Docker Compose file
```
version: '3.1'
services:
  oracle-db:
    privileged: true
    container_name: oracle
    #image: container-registry.oracle.com/database/enterprise:latest
    # image: container-registry.oracle.com/database/free:latest
    image: container-registry.oracle.com/database/adb-free:latest-23ai    
    environment:
      - WORKLOAD_TYPE=ATP
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - WALLET_PASSWORD=YourP@ssword321#_
      - ADMIN_PASSWORD=YourP@ssword321#_
    ports:
      - 1521:1521
      - 1522:1522
      - 8443:8443
      - 27017:27017
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup    
volumes:
  oracle-data:
  oracle-backup:
```

**Comment by ahmetsevki** [comment]
I think the issue is I have `ORACLE_SID=ORCLCDB` in the environment variables. Because there is a `/u01/app/oracle/product/23.0.0.0/dbhome_1/dbs/init.ora` file.

**Comment by aosingh** [comment]
@ahmetsevki Please try with this

```yaml
version: '3.8'
services:
  adb-free:
    image: ghcr.io/oracle/adb-free:latest
    ports:
      - "1521:1522"
      - "1522:1522"
      - "8443:8443"
      - "27017:27017"
    environment:
      - WORKLOAD_TYPE=ATP
      - DATABASE_NAME=MYATP 
      - WALLET_PASSWORD=YourP@ssword321#_
      - ADMIN_PASSWORD=YourP@ssword321#_
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
```
