### ISSUE TITLE
Latest version (23.10.2.3) fails to 'docker compose up' 

### ISSUE THREAD

**Issue by edoardodavini** [oracle/adb-free#7]
Hi everyone, I've a simple `docker compose` 

```
version: "3"
services:
  database:
    container_name: retraced.oracledb-2130-atp
    image: ghcr.io/oracle/adb-free:latest
    environment:
      - MY_ATP_ADMIN_PASSWORD=my_nice_atp_pw
      - MY_ADW_ADMIN_PASSWORD=my_nice_adw_pw
      - MY_ADB_WALLET_PASSWORD=my_nice_wallet_pw
    ports:
      - 1521:1521 # TLS
      - 1522:1522 # mTLS
      - 8443:8443 # HTTPS for ORDS/APEX
      - 27017:27017 # Mongo API
    hostname: localhost
    cap_add: 
      - SYS_ADMIN
```

As you can see, I'm getting this error
```
retraced.oracledb-2130-atp  |   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_sysaux_lsccg3wz_.dbf  
retraced.oracledb-2130-atp  |   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_data_lsccg3y1_.dbf  
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/0E10A174E5A0408DE0636402000A759D/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/0E10A174E5A0408DE0636402000A759D/datafile/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/onlinelog/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/0E1099BA25FC3D75E0636402000ADF30/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/0E1099BA25FC3D75E0636402000ADF30/datafile/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/0E10A7FCACD24110E0636402000AF7B6/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/0E10A7FCACD24110E0636402000AF7B6/datafile/
retraced.oracledb-2130-atp  |    creating: /u01/app/oracle/oradata/POD1/controlfile/
retraced.oracledb-2130-atp  |   inflating: /u01/app/oracle/oradata/POD1/controlfile/o1_mf_lscctrtj_.ctl  
retraced.oracledb-2130-atp  | TIME ELAPSED Unzipping /u01/POD1.zip: 0 minutes and 31 seconds elapsed
retraced.oracledb-2130-atp  | User input JSON not found
retraced.oracledb-2130-atp  | Traceback (most recent call last):
retraced.oracledb-2130-atp  |   File "/u01/scripts/user_input.py", line 89, in <module>
retraced.oracledb-2130-atp  |     generate_default_input_json()
retraced.oracledb-2130-atp  |   File "/u01/scripts/user_input.py", line 64, in generate_default_input_json
retraced.oracledb-2130-atp  |     workload_type = os.getenv("WORKLOAD_TYPE").upper()
retraced.oracledb-2130-atp  | AttributeError: 'NoneType' object has no attribute 'upper'
retraced.oracledb-2130-atp exited with code 1
``` 

![image](https://github.com/oracle/adb-free/assets/65487465/861d339e-dae8-490e-b86f-d35256e7da7d)

Reverting to v`23.10.2.2` fixes the issue

Just noticed that v`23.10.2.2` is 2.01GB and `23.10.2.3` is 1.3GB

Pretty big difference huh?

**Comment by aosingh** [comment]
Hi @edoardodavini 

Thanks for reporting the issue. Starting with version `23.10.2.3`, the environment variables for startup are simplified.

You can start the container with environment variable `WORKLOAD_TYPE=ATP` or `WORKLOAD_TYPE=ADW` 

The passwords are called `ADMIN_PASSWORD` and `WALLET_PASSWORD`. 

Please try the below docker-compose configuration. 

```yaml
version: "3"
services:
  database:
    container_name: retraced.oracledb-2130-atp
    image: ghcr.io/oracle/adb-free:latest
    environment:
      - WORKLOAD_TYPE=ATP
      - ADMIN_PASSWORD=my_nice_atp_pw
      - WALLET_PASSWORD=my_nice_wallet_pw
    ports:
      - 1521:1521 # TLS
      - 1522:1522 # mTLS
      - 8443:8443 # HTTPS for ORDS/APEX
      - 27017:27017 # Mongo API
    hostname: localhost
    cap_add: 
      - SYS_ADMIN
```
